import React from 'react';
import {Inter} from 'next/font/google';

import {AppHeader} from '@forest-feed/components/kit/AppHeader';
import './globals.css';

const inter = Inter({subsets: ['latin']});

export type RootLayoutProps = {
  text: string;
  children: React.ReactNode;
};

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: RootLayoutProps) {
  const {text, children} = props;
  return (
    <html lang="en">
      <body className={`${inter.className} bg-primaryBg`}>
        <AppHeader text="hello" />
        <div>{children}</div>
      </body>
    </html>
  );
}
