import React from 'react';
import {Inter} from 'next/font/google';
import {redirect} from 'next/navigation';
import {NextIntlClientProvider} from 'next-intl';

import './globals.css';
import {AppHeader} from '@forest-feed/components/layout/AppHeader';
import {Navbar} from '@forest-feed/components/Navbar';

const inter = Inter({subsets: ['latin']});

export type RootLayoutProps = {
  params: {locale: string};
  children: React.ReactNode;
};

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'fa'}];
}

export default async function LocaleLayout(props: RootLayoutProps) {
  const {
    params: {locale},
    children,
  } = props;

  let messages;
  try {
    messages = (await import(`../../localization/${locale}.json`)).default;
  } catch (error) {
    return redirect('/en');
  }

  return (
    <html lang={locale}>
      <body className={`${inter.className} bg-primaryBg`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div className="container mx-auto">
            <div className="grid grid-cols-6 gap-20">
              <div className="grid col-span-6">
                <AppHeader walletAddress="0x21212121212121212121212" />
              </div>
              <div className="col-span-1">
                <Navbar />
              </div>
              <div className="col-span-5">{children}</div>
            </div>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
